### PR TITLE
Support Boost 1.71 (Ubuntu 20.04 Humble)

### PR DESCRIPTION
**Pull request by roncapat**
Tentative fix for #66.
Issue introduced in #65.

Boost 1.71 API: https://www.boost.org/doc/libs/1_71_0/doc/html/boost/circular_buffer.html

### CODE REVIEW

**Comment by jonbinney** [comment]
Looks like tests passed on humble, iron, and rolling. @sandro-meier could you verify that this fixes your compilation error?

**Comment by ghost** [comment]
Yes works! Thanks for the absolutely amazing turn-around time of fixing this :partying_face:

**Comment by jonbinney** [comment]
Great! Merging.

**Comment by roncapat** [comment]
Happy this works out of the box for both versions, the included test case should guarantee no surprises come up when using the new API :)
