### ISSUE TITLE
Iterable circular_buffer compilation broken with boost 1.71

### ISSUE THREAD

**Issue by ghost** [ros/filters#66]
Hi all, 

Trying to compile `filters` with ros2 humble and boost `1.71`. Unfortunately, that is broken: 

```
Starting >>> filters
--- stderr: filters
In file included from /home/dev_ws/src/filters/test/test_realtime_circular_buffer.cpp:35:
/home/dev_ws/src/filters/include/filters/realtime_circular_buffer.hpp: In instantiation of ‘filters::RealtimeCircularBuffer<T>::const_iterator filters::RealtimeCircularBuffer<T>::begin() const [with T = int; filters::RealtimeCircularBuffer<T>::const_iterator = boost::cb_details::iterator<boost::circular_buffer<int, std::allocator<int> >, boost::cb_details::const_traits<boost::cb_details::allocator_traits<std::allocator<int> > > >]’:
/home/dev_ws/src/filters/test/test_realtime_circular_buffer.cpp:64:25:   required from here
/home/dev_ws/src/filters/include/filters/realtime_circular_buffer.hpp:91:16: error: ‘const class boost::circular_buffer<int, std::allocator<int> >’ has no member named ‘cbegin’; did you mean ‘begin’?
   91 |     return cb_.cbegin();
      |            ~~~~^~~~~~
      |            begin
/home/dev_ws/src/filters/include/filters/realtime_circular_buffer.hpp: In instantiation of ‘filters::RealtimeCircularBuffer<T>::const_iterator filters::RealtimeCircularBuffer<T>::end() const [with T = int; filters::RealtimeCircularBuffer<T>::const_iterator = boost::cb_details::iterator<boost::circular_buffer<int, std::allocator<int> >, boost::cb_details::const_traits<boost::cb_details::allocator_traits<std::allocator<int> > > >]’:
/home/dev_ws/src/filters/test/test_realtime_circular_buffer.cpp:64:25:   required from here
/home/dev_ws/src/filters/include/filters/realtime_circular_buffer.hpp:100:16: error: ‘const class boost::circular_buffer<int, std::allocator<int> >’ has no member named ‘cend’; did you mean ‘end’?
  100 |     return cb_.cend();
      |            ~~~~^~~~
      |            end
make[2]: *** [CMakeFiles/realtime_buffer_test.dir/build.make:63: CMakeFiles/realtime_buffer_test.dir/test/test_realtime_circular_buffer.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:569: CMakeFiles/realtime_buffer_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:141: all] Error 2
```

This change was introduced in #65 . I confirmed that compilation with `5507bc5175cb74e825ee20b9dc19e67ef6a4a022` (the last commit before the merge of #65 is successful.

**Comment by ghost** [comment]
@roncapat FYI

**Comment by roncapat** [comment]
Will check for sure!

**Comment by jonbinney** [comment]
I'll take a look at setting up CI for PRs to catch this earlier next time. Sorry!

**Comment by jonbinney** [comment]
Adding CI here: https://github.com/ros/filters/pull/67

**Comment by jonbinney** [comment]
Hmmm.... looks like CI was already running for us on the build farm. Not sure why it didn't catch this

**Comment by jonbinney** [comment]
I've added a branch protection rule to make sure I don't miss any CI checks for the ros2 branch in the future.

**Comment by roncapat** [comment]
Just a comment... why don't we have here branches for each ros2 version? Or at least start branching out humble and iron?

**Comment by jonbinney** [comment]
As long as all changes are backwards compatible, it makes it easier (avoids needing to backport things).

**Comment by roncapat** [comment]
If everything is ok maybe we should close this :)
